#!/usr/bin/env bash

# script to run phpmyadmin in a docker container either pointing to an provided address or providing an interface to enter it.
#
# Usage: docker_phpmyadmin

# m.opitz@qmul.ac.uk | 2020-02-20
version="1.3"
docker rm -f phpmyadmin >/dev/null 2>/dev/null

# the default port
port=8000

usage() {
	echo "docker_phpmyadmin [-p <port>] [server_name]"
}

# get port option
while getopts ":hp:" x; do
    case "${x}" in
        h)
            usage
            ;;
        p)
            port=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

echo "DockerPhpMyAdmin v.$version"
inuse=$(sudo netstat -anp tcp | grep -i "listen" | grep ${port})
if [[ ! -z "$inuse" ]]; then
	echo "==> ERROR! Port ${port} is already in use! Aborting..."
	exit 1
fi
if [ $# -eq 0 ]
then
	docker run -d -p ${port}:80 --name phpmyadmin -e PMA_ARBITRARY=1 phpmyadmin/phpmyadmin > /dev/null
	echo "==> Now enter 'localhost:${port}' into your browser."
else
	ip=$1
	if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		docker run -d -p ${port}:80 --name phpmyadmin -e PMA_HOST=$1 phpmyadmin/phpmyadmin >/dev/null
		echo "==> connected to $1"
		echo "==> Now enter 'localhost:${port}' into your browser."
	else
		echo "==> $ip is not a valid IP address, skipping..."
		docker run -d -p ${port}:80 --name phpmyadmin -e PMA_ARBITRARY=1 phpmyadmin/phpmyadmin > /dev/null
	fi
fi
